# -*- coding: utf-8 -*-
"""_init_.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lrctwN-AWdFHgotmPxw7dw-CSmamoqHZ
"""

from .func_dict_1 import
from .func_dict_2 import popular_words
from .func_dict_3 import count_words

__all__ = (
           'popular_words', 'count_words',
          )