# -*- coding: utf-8 -*-
"""code.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17JDAukz5Ne919BgF8PrmZvVEj-_3A2YA
"""

def count_words(input_line):
  new_lst = list(input_line.split())
  lst_words = []
  lst_ind = []
  idx = 0

  for i in range(len(new_lst)):
    if new_lst[i] not in lst:
      lst.append(-1)
    else:
      idx = new_lst.index(new_lst[i])
      lst.append(idx)

  return lst