# -*- coding: utf-8 -*-
"""code.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17JDAukz5Ne919BgF8PrmZvVEj-_3A2YA
"""

def popular_words(input_line):
  dct ={}
  lst = []
  lst_words = list(input_line.split())

  for i in range(len(lst_words)):
    if lst_words[i] not in dct:
      dct[lst_words[i]] = 0
    else:
      dct[lst_words[i]] += 1

  for k,v in dct.items():
    if v >= max(dct.values()):
      lst.append(k)

  return sorted(lst)